version: '3.2'
services:
  rabbitmq_bootcamp:
    build:
      context: ./rabbitmq
    image: douglasrcampos/rabbitmq_bootcamp:latest
    ports:
      - 15672:15672
      - 5672:5672
    container_name: rabbitmq_bootcamp
    networks:
      - backend
  postgres_bootcamp:
    build:
      context: ./postgres
    image: douglasrcampos/postgres_bootcamp:latest
    ports:
      - 5432:5432
    container_name: postgres_bootcamp
    networks:
      - backend
  app-user-api:
    build:
      context: ../douglas-campos-backend/app-user-api
      dockerfile: ../app-user-api/Dockerfile
    image: douglasrcampos/app-user-api:latest
    command: ["--debug"]
    ports:
      - 8081:8081
    container_name: app-user-api
    environment:
      - RABBIT_HOST=rabbitmq_bootcamp
      - POSTGRES_URL=postgres_bootcamp
      - POSTGRES_USER=bootcamp
      - POSTGRES_PASSWORD=bootcamppass
      - POSTGRES_DATABASE=bootcamp
    depends_on:
      - postgres_bootcamp
    networks:
      - backend
  app-integration-api:
    build:
      context: ../douglas-campos-backend/app-integration-api
      dockerfile: ../app-integration-api/Dockerfile
    image: douglasrcampos/app-integration-api:latest
    ports:
      - 8082:8082
    container_name: app-integration-api
    environment:
      - RABBIT_HOST=rabbitmq_bootcamp
      - POSTGRES_URL=postgres_bootcamp
      - POSTGRES_USER=bootcamp
      - POSTGRES_PASSWORD=bootcampass
      - POSTGRES_DATABASE=bootcamp
      - CLIENT_ID = 00a5fc853d8949cd8f56e5fca2a77556
      - CLIENT_SECRET = 62bbeeb6dc1b4907a8b1504fb8515793
    depends_on:
      - postgres_bootcamp
    networks:
      - backend
networks:
  backend:
    driver: "bridge"


